name: chopper_example
description: Example usage of the Chopper package
version: 0.0.1
documentation: https://hadrien-lejard.gitbook.io/chopper/
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  chopper: ^3.0.0
  json_annotation: ^4.0.0
  built_value: ^8.0.0
  analyzer: ^1.2.0

dev_dependencies:
  build_runner: ^1.12.1
  chopper_generator: ^3.0.6
  build_web_compilers: ^2.0.0
  json_serializable: ^4.0.2
  built_value_generator: ^8.0.0

dependency_overrides:
# chopper:
#   path: ../chopper
# chopper_generator:
#   path: ../chopper_generator
 