# Created with package:mono_repo v3.4.7
name: Dart CI
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - name: mono_repo self validate
        run: pub global activate mono_repo 3.4.7
      - name: mono_repo self validate
        run: pub global run mono_repo generate --validate
  job_002:
    name: "analyzer_and_format; PKGS: chopper, chopper_built_value, chopper_generator; `dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value-chopper_generator;commands:dartfmt-dartanalyzer"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value-chopper_generator
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - id: chopper_pub_upgrade
        name: "chopper; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper
        run: pub upgrade --no-precompile
      - name: "chopper; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.chopper_pub_upgrade.conclusion == 'success'"
        working-directory: chopper
        run: dartfmt -n --set-exit-if-changed .
      - name: "chopper; dartanalyzer --fatal-infos ."
        if: "always() && steps.chopper_pub_upgrade.conclusion == 'success'"
        working-directory: chopper
        run: dartanalyzer --fatal-infos .
      - id: chopper_built_value_pub_upgrade
        name: "chopper_built_value; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper_built_value
        run: pub upgrade --no-precompile
      - name: "chopper_built_value; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.chopper_built_value_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_built_value
        run: dartfmt -n --set-exit-if-changed .
      - name: "chopper_built_value; dartanalyzer --fatal-infos ."
        if: "always() && steps.chopper_built_value_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_built_value
        run: dartanalyzer --fatal-infos .
      - id: chopper_generator_pub_upgrade
        name: "chopper_generator; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper_generator
        run: pub upgrade --no-precompile
      - name: "chopper_generator; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.chopper_generator_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_generator
        run: dartfmt -n --set-exit-if-changed .
      - name: "chopper_generator; dartanalyzer --fatal-infos ."
        if: "always() && steps.chopper_generator_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_generator
        run: dartanalyzer --fatal-infos .
  job_003:
    name: "unit_test; PKGS: chopper, chopper_built_value; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - id: chopper_pub_upgrade
        name: "chopper; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper
        run: pub upgrade --no-precompile
      - name: chopper; pub run test
        if: "always() && steps.chopper_pub_upgrade.conclusion == 'success'"
        working-directory: chopper
        run: pub run test
      - id: chopper_built_value_pub_upgrade
        name: "chopper_built_value; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper_built_value
        run: pub upgrade --no-precompile
      - name: chopper_built_value; pub run test
        if: "always() && steps.chopper_built_value_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_built_value
        run: pub run test
    needs:
      - job_001
      - job_002
  job_004:
    name: "unit_test; PKGS: chopper, chopper_built_value; `pub run test -p chrome`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - id: chopper_pub_upgrade
        name: "chopper; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper
        run: pub upgrade --no-precompile
      - name: "chopper; pub run test -p chrome"
        if: "always() && steps.chopper_pub_upgrade.conclusion == 'success'"
        working-directory: chopper
        run: pub run test -p chrome
      - id: chopper_built_value_pub_upgrade
        name: "chopper_built_value; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper_built_value
        run: pub upgrade --no-precompile
      - name: "chopper_built_value; pub run test -p chrome"
        if: "always() && steps.chopper_built_value_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_built_value
        run: pub run test -p chrome
    needs:
      - job_001
      - job_002
  job_005:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - id: upload_coverage
        name: chopper; tool/coverage.sh
        if: "always() && steps.checkout.conclusion == 'success'"
        run: bash tool/coverage.sh
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
